export const SHOW_PRODUCT_MODAL = 'SHOW_PRODUCT_MODAL';
export const SHOW_PRODUCT_MODAL_CONTENT = 'SHOW_PRODUCT_MODAL_CONTENT';
export const HIDE_PRODUCT_MODAL = 'HIDE_PRODUCT_MODAL';
export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
